---
- name: up node-exporter
  become: true
  community.docker.docker_swarm_service:
    name: Node-exporter
    image: "prom/node-exporter:{{ node_exporter_version }}"
    #state: "present" #используется по умолчанию
    networks:
      - name: "{{ network_name }}"
    publish:
      - published_port: 9100
        target_port: 9100
        protocol: tcp
    replicas: 2
    mounts:
      - source: /proc
        target: /host/proc:ro
      - source: /sys
        target: /host/sys:ro
      - source: /
        target: /rootfs:ro
### + вставка
#     - /etc/hostname:/etc/nodename
#      - source: /etc/hostname
#        target: /etc/nodename
#    command:
#      - '--path.procfs=/host/proc'
#      - '--path.sysfs=/host/sys'
#      - '--collector.filesystem.ignored-mount-points'
#      - '^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)'
###
#      - '--path.procfs=/host/proc'
#      - '--path.rootfs=/rootfs'
#      - '--path.sysfs=/host/sys'
#      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
#

#    volumes:
#      - /proc:/host/proc:ro
#      - /sys:/host/sys:ro
#      - /:/rootfs:ro
#      - /etc/hostname:/etc/nodename
#    command:
#      - '--path.sysfs=/host/sys'
#      - '--path.procfs=/host/proc'
#      - '--collector.textfile.directory=/etc/node-exporter/'
#      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
#      - '--no-collector.ipvs'

