---
- name: deploy Alertmanager
  become: true
  community.docker.docker_swarm_service:
    name: Alertmanager
    image: "prom/alertmanager:{{ alertmanager_version }}"
    replicas: 1
    networks:
      - name: "{{ network_name }}"
    publish:
      - published_port: 9093
        target_port: 9093
#    command:
#      - '--config.file=/etc/alertmanager/alertmng_config.yml'
#      - '--config.file=/etc/alertmanager/alertmanager.yml'
#      - '--storage.path=/alertmanager'
    mounts:
      - source: "{{ monitoring_folder }}/alertmanager/"
        target: /etc/alertmanager/
      - source: "/etc/localtime"
        target: /etc/localtime:ro
      - source: "/etc/timezone"
        target: /etc/timezone:ro
#      - source: "./templates.txt"
#        target: /etc/alertmanager/templates/templates.txt

    configs:
      - config_name: alertmanager.yml
#        filename: /etc/alertmanager/config.yml
        filename: /etc/alertmanager/alertmanager.yml
        mode: 0444
    placement:
      constraints:
        - node.labels.key1 == monitoring

# /etc/alertmanager/alertmanager.yml
###от Жени
#   volumes:
#      - ./:/etc/alertmanager/
#      - /etc/localtime:/etc/localtime:ro
#      - /etc/timezone:/etc/timezone:ro
#      - ./templates.txt:/etc/alertmanager/templates/templates.txt
#    command:
#      - --config.file=/etc/alertmanager/alertmanager.yml
#      - --storage.path=/alertmanager
#      - --log.level=debug
